### ISSUE TITLE
Wrong comment

### ISSUE THREAD

**Issue by matzeema** [ardera/flutter_gpiod#12]
In the `GpioChip` class ([file](https://github.com/ardera/flutter_gpiod/blob/master/lib/src/gpiod.dart)), in the comments of the string `label` it says:
```dart
 /// This is the hardware label of the underlying GPIO device.
 /// The main GPIO chip of the Raspberry Pi 4 has the label
 /// `brcm2835-pinctrl` for example.
```
But the label of of the main GPIO chip is `pinctrl-bcm2835`.

**Comment by ardera** [comment]
Updated it, thanks
