### ISSUE TITLE
How to read data？

### ISSUE THREAD

**Issue by tsuiwade** [ardera/flutter_gpiod#15]
I‘m using temperature sensor with 'one wire' protocol . 
So how to read data with your GPIO code?
plz!

**Comment by ardera** [comment]
I don't think that's a good idea. Using GPIO bitbanging to interface a one wire bus inside flutter is probably going to be super unstable. Instead, I'd try interfacing the 1 wire sysfs drivers.

**Comment by tsuiwade** [comment]
Thanks!
Closing the issue.
