### ISSUE TITLE
Best way to get linehandle from SignalEvent

### ISSUE THREAD

**Issue by mortenboye** [ardera/flutter_gpiod#4]
Im looking at subscribing to events from multiple gpis inputlines and in my shared event handler I would like to be able to tell which line an event is coming from. What's the preferred way to do this?

**Comment by ardera** [comment]
There's no integrated way for doing this, but I think the best way to accomplish that is by using [dart extension methods](https://dart.dev/guides/language/extension-methods) (needs dart >= 2.7) and the [tuple package](https://pub.dev/packages/tuple):
```dart
import 'package:tuple/tuple.dart';

. . .

extension SignalEventWithLine on GpioLine {
  Tuple2<GpioLine, SignalEvent> get onSignalEventWithLine
    => onSignalEvent.map((signalEvent) => Tuple2(this, signalEvent));
}

. . .
```

Then you can just listen to it like any other stream and do stuff like:
```dart
/// `line` is a GpioLine of your choice
final sub = line.onSignalEventWithLine.listen(
  (tuple) => print("gpio line: ${tuple.first}, signal event: ${tuple.second}")
);
```

**Comment by mortenboye** [comment]
Nice solution, thank you.
