### ISSUE TITLE
migrate to dart:ffi

### ISSUE THREAD

**Issue by ardera** [ardera/flutter_gpiod#5]
Use `dart:ffi` instead of platform channels for better performance.

EDIT: This will also make the API a lot nicer, since a lot of `async` stuff can go away or be made synchronous.

**Comment by DisDis** [comment]
I started it. First step is ffi_gpiod.

**Comment by DisDis** [comment]
https://pub.dev/packages/gpiod

**Comment by matzeema** [comment]
Thanks for the work @DisDis

**Comment by DisDis** [comment]
I am creating a prototype https://github.com/DisDis/gpiod/blob/master/example/main.dart , but currently it does not work :(

**Comment by DisDis** [comment]
I turned on LED.

**Comment by DisDis** [comment]
I published new version, https://pub.dev/packages/gpiod/versions/0.1.0#-example-tab- , I ported only 3 methods(gpiodp_request_line, gpiodp_ensure_gpiod_initialized, gpiodp_get_config) in current moment.  https://github.com/DisDis/gpiod/blob/master/lib/src/utils.dart

**Comment by ardera** [comment]
Nice work @DisDis !
I'm not sure we need the pthread bindings though, dart's isolates have no shared memory (i.e. nothing to use a mutex for) and the only way for inter-thread communication is message passing

My plan was to have a dart "line event listener" isolate which just repeatedly calls epoll_wait and sends anything that it receives from epoll back to the UI (main) isolate, so no need for pthreads I think

**Comment by DisDis** [comment]
I changed my plan. I im focusing to FFI proxy_gpiod with methods and will replace implementation in flutter_gpiod:
-        return  gpiodp_get_num_chips(object, responsehandle);
-        return gpiodp_get_chip_details(object, responsehandle);
-        return gpiodp_get_line_handle(object, responsehandle);
-        return gpiodp_get_line_details(object, responsehandle);
-        return gpiodp_request_line(object, responsehandle);
-        return gpiodp_release_line(object, responsehandle);
-        return gpiodp_reconfigure_line(object, responsehandle);
-        return gpiodp_get_line_value(object, responsehandle);
-        return gpiodp_set_line_value(object, responsehandle);
-        return gpiodp_supports_bias(object, responsehandle);
-        return gpiodp_supports_reconfiguration

because pthread is not dynamic library:(

**Comment by DisDis** [comment]
@ardera Yes, but it will be easier if you use FFI async callback( nativ_port ) https://github.com/dart-lang/sdk/blob/master/samples/ffi/async/sample_native_port_call.dart
I will try it today. Because native pthread work faster.

**Comment by DisDis** [comment]
First iteration https://github.com/DisDis/gpiod/blob/master/example/main.dart
I turned on LED. Not all methods migrated. ( https://github.com/DisDis/gpiod/blob/master/lib/src/bindings/proxy_gpiod/bindings.dart#L31 
)

**Comment by DisDis** [comment]
@ardera 
Uff. I released stable release(all functions are implemented and worked). It has been a long way.
Can you review the code? https://github.com/DisDis/gpiod
Do you agree if I write you in the authors?
Can we specify a MIT license?
https://pub.dev/packages/gpiod

TODO: Need to finish error handling.

**Comment by ardera** [comment]
> Can you review the code?

I can do that, I don't have time at the moment though
Since you gave me commit access, I assume I should just push my changes (if any) to the repo directly instead of Pull Requests etc?
One thing I noticed was that memory allocated using [`allocate`](https://pub.dev/documentation/ffi/latest/ffi/allocate.html) (which is called in the `allocate` factory of Structs for example, like `LineDetails.allocate`) also has to be freed using [`free`](https://pub.dev/documentation/ffi/latest/ffi/free.html).

> Do you agree if I write you in the authors?

Yeah I agree

> Can we specify a MIT license?

Don't know what you mean by that, flutter-pi, flutter_gpiod and your gpiod are all licensed under MIT

Just as a general clarification: Should your `gpiod` package exist as a separate package to `flutter_gpiod`? (kinda looks like that because its called ProxyGpiod and not FlutterGpiod anymore)
My original thought was to upstream `gpiod` into my `flutter_gpiod`, and call it version 1.0.0 at that point. The native C-code you wrote could then be included into `flutter-pi`. That'd be more convenient to the user IMO

**Comment by matzeema** [comment]
> Just as a general clarification: Should your gpiod package exist as a separate package to flutter_gpiod? (kinda looks like that because its called ProxyGpiod and not FlutterGpiod anymore)

Maybe thats a good point to restructure flutter-pi packages. The problem with the current system is that even if you don't use the `gpiod` package, it is installed with flutter-pi. This might also open the door for other developers to publish some packages and make flutter-pi even more useable.

**Comment by ardera** [comment]
> Maybe thats a good point to restructure flutter-pi packages. The problem with the current system is that even if you don't use the `gpiod` package, it is installed with flutter-pi. This might also open the door for other developers to publish some packages and make flutter-pi even more useable.

That's true, but that's kinda a luxury problem IMO. That's probably a few kilobytes of disk space. Also, you can exclude the gpiod plugin at build-time by taking away the `-DBUILD_GPIOD_PLUGIN` build flag in the Makefile. I agree though that plugin maintainers (if any) should be able to update their plugin independently of me, i.e. without having to ask for my explicit approval for every single change (pull request).

But 

- We can't make `flutter-pi` plugins work similiar to the way android, iOS, windows, macOS & linux desktop plugins work, with the platform-side code of any plugins just residing in the apps source directory (`/android`, `/ios`, `/windows`, etc). That's just not feasible.
- It may be possible to have a `/usr/lib/flutter-pi-modules/` directory which contains plugin code that will be dynamically loaded when an app is launched. But I can't think of a nice way for managing this modules directory.

**Comment by DisDis** [comment]
Ok guys. I returned.
My todo:
1. I will deal with error handling.
2. Add free for all calls.

`Don't know what you mean by that, flutter-pi, flutter_gpiod and your gpiod are all licensed under MIT`
I missed this :(

'The native C-code you wrote could then be included into flutter-pi'
FFI works only with dynamic library. I believe that the package gpiod must work without flutter.  It is very useful for testing and debugging. Because you can run 'dart server-service-side.dart' and you receive remote debug in IDE.

**Comment by ardera** [comment]
> FFI works only with dynamic library.

Are you sure? I thought that's what [`DynamicLibrary.executable`](https://api.dart.dev/dev/2.9.0-13.0.dev/dart-ffi/DynamicLibrary/DynamicLibrary.executable.html) and  [`DynamicLibrary.process`](https://api.dart.dev/dev/2.9.0-13.0.dev/dart-ffi/DynamicLibrary/DynamicLibrary.process.html) are for



> I believe that the package gpiod must work without flutter. It is very useful for testing and debugging. Because you can run 'dart server-service-side.dart' and you receive remote debug in IDE.

That's okay, then gpiod will be independent of flutter and flutter_gpiod will require flutter.

**Comment by DisDis** [comment]
> Are you sure? I thought that's what DynamicLibrary.executable and DynamicLibrary.process are for ...

:facepalm: I missed this :(  I could try calling pthread and epoll methods...in the first implementation.

> That's okay, then gpiod will be independent of flutter and flutter_gpiod will require flutter.

What code will you have in flutter_gpiod?

**Comment by DisDis** [comment]
i published version 1.0.1, added error handlers.
