### ISSUE TITLE
Hardware PWM support

### ISSUE THREAD

**Issue by matzeema** [ardera/flutter_gpiod#6]
An implementation for hardware PWM would be nice. Software PWM works fine (I already tested it) but it needs a lot of power.

**Comment by ardera** [comment]
That a good idea, but I think that's out of the scope of this project. Could be realised pretty easily though, you don't even need ffi. All it takes is writing some stuff into some sysfs files, like described [here](https://jumpnowtek.com/rpi/Using-the-Raspberry-Pi-Hardware-PWM-timers.html)

**Comment by matzeema** [comment]
I already have done an [implementation](https://github.com/matzesoft/kart-project/tree/master/lib/interfaces/pwm_interface) in my `flutter-pi` project using [wiringPi](http://wiringpi.com) with dart:ffi.
So for anyone else who also wants to implement PWM - choose whats easier to you.
