### ISSUE TITLE
Button does not work

### ISSUE THREAD

**Issue by DisDis** [ardera/flutter_gpiod#7]
I have problem with button. I have code:
```Dart
    final line15 =
    chips.singleWhere((chip) => chip.label == 'pinctrl-bcm2835').lines[15];
    
    await line15.requestInput(
        consumer: "BUTTON",
        activeState: ActiveState.high,
        triggers: {SignalEdge.falling, SignalEdge.rising});
    
    /// Log line events for eternity.
    line15.onEvent.listen((event) {
      print("Button: $event");
    });
```

It doesn't work. But if i execute python ./button.py and exit, my code starts to work.
```python
// button.py
import RPi.GPIO as GPIO # Import Raspberry Pi GPIO library
def button_callback(channel):
    print("Button was pushed!")
GPIO.setwarnings(False) # Ignore warning for now
GPIO.setmode(GPIO.BOARD) # Use physical pin numbering
GPIO.setup(10, GPIO.IN, pull_up_down=GPIO.PUD_DOWN) # Set pin 10 to be an input pin and set initial value to be pulled low (off)
GPIO.add_event_detect(10,GPIO.RISING,callback=button_callback) # Setup event on pin 10 rising edge
message = input("Press enter to quit\n\n") # Run until someone presses enter
GPIO.cleanup() # Clean up
```

**Comment by ardera** [comment]
Can you try doing a full reboot and execute your flutter code right after that? (in the best case, reboot, login and execute flutter-pi)

If it doesn't work then, can you give me the outputs of `lsgpio` before and while flutter is running.
You can also try running `gpiomon 0 15` to listen to BCM15 from shell. (Please don't execute your python script before any of those commands either)

The Raspberry Pi has a long history of GPIO interfaces:

- first, people accessed GPIO by accessing the hardware themselves (i.e. mapping `/dev/mem`), which is very very __bad__
- then, the sysfs interface was used
- now, the newer gpiodev / gpiod (`/dev/gpiochipX`) should be used

For example, I think wiringPi uses the first way, I think `RPi.GPIO` uses the 2nd way and flutter-pi of course uses the 3rd way, the gpiod interface.

The inter-compatibility of these interfaces isn't clear, i.e. I'm not sure you can use the sysfs and gpiod concurrently. (Accessing the raw hardware is of course the most incompatible option of them all, that'll basically result in the kernel driver and the userspace process concurrently accessing the GPIO memory)

In practice, these different interfaces will cause all sorts of strange problems. For example, I had the problem that I couldn't get any line events at all inside flutter after I ran a specific program. Turns out that program was accessing the GPIO memory directly.

**Comment by DisDis** [comment]
Can you try doing a full reboot and execute your flutter code right after that? 
After reboot my code does not work

**Comment by ardera** [comment]
> If it doesn't work then, can you give me the outputs of `lsgpio` before and while flutter is running.
> You can also try running `gpiomon 0 15` to listen to BCM15 from shell. (Please don't execute your python script before any of those commands either)

What about this?

**Comment by DisDis** [comment]
@ardera 
1. reboot.

gpioinfo
```
gpiochip0 - 54 lines:
	line   0:      unnamed       unused   input  active-high 
// CUT
	line  11:      unnamed       unused   input  active-high 
	line  12:      unnamed       unused   input  active-high 
	line  13:      unnamed       unused   input  active-high 
	line  14:      unnamed       unused   input  active-high 
	line  15:      unnamed       unused   input  active-high 
	line  16:      unnamed       unused   input  active-high 
	line  17:      unnamed       unused   input  active-high 
	line  18:      unnamed       unused   input  active-high 
	line  19:      unnamed       unused   input  active-high 
gpiochip1 - 8 lines:
	line   0:      "BT_ON"       unused   input  active-high 
	line   1:      "WL_ON"       unused   input  active-high 
	line   2: "PWR_LED_OFF" "led1" output active-low [used]
	line   3: "GLOBAL_RESET" unused input active-high 
	line   4: "VDD_SD_IO_SEL" "vdd-sd-io" output active-high [used]
	line   5:   "CAM_GPIO"       unused   input  active-high 
	line   6:      unnamed     "vcc-sd"  output  active-high [used]
	line   7:      unnamed       unused   input  active-high 
gpiochip2 - 2 lines:
	line   0:      unnamed       unused   input  active-high 
	line   1:      unnamed       unused   input  active-high
```
2. flutter_gpio_test - **BUTTON does'n work**
`flutter: 15:  LineInfo(consumer: 'BUTTON', direction:  input, isUsed: true, isRequested: true, isFree: false)`


gpioinfo - (Done in parallel)
```
gpiochip0 - 54 lines:
// CUT
	line  14:      unnamed "flutter_gpiod test" output active-high [used]
	line  15:      unnamed     "BUTTON"   input  active-high [used]
	line  16:      unnamed       unused   input  active-high 
	line  17:      unnamed        "PIR"   input  active-high [used]
gpiochip1 - 8 lines:
	line   0:      "BT_ON"       unused   input  active-high 
	line   1:      "WL_ON"       unused   input  active-high 
	line   2: "PWR_LED_OFF" "led1" output active-low [used]
	line   3: "GLOBAL_RESET" unused input active-high 
	line   4: "VDD_SD_IO_SEL" "vdd-sd-io" output active-high [used]
	line   5:   "CAM_GPIO"       unused   input  active-high 
	line   6:      unnamed     "vcc-sd"  output  active-high [used]
	line   7:      unnamed       unused   input  active-high 
gpiochip2 - 2 lines:
	line   0:      unnamed       unused   input  active-high 
	line   1:      unnamed       unused   input  active-high 

```

3. exit flutter_gpio_test

4. gpioinfo
```
gpiochip0 - 54 lines:
	line   0:      unnamed       unused   input  active-high 
//CUT
	line  10:      unnamed       unused   input  active-high 
	line  11:      unnamed       unused   input  active-high 
	line  12:      unnamed       unused   input  active-high 
	line  13:      unnamed       unused   input  active-high 
	line  14:      unnamed       unused  output  active-high 
	line  15:      unnamed       unused   input  active-high 
	line  16:      unnamed       unused   input  active-high 
	line  17:      unnamed       unused   input  active-high 
	line  18:      unnamed       unused   input  active-high 
	line  19:      unnamed       unused   input  active-high 

```
4. python (run & exit)
gpioinfo 
```
gpiochip0 - 54 lines:
	line   0:      unnamed       unused   input  active-high 
	line   1:      unnamed       unused   input  active-high 
	line   2:      unnamed       unused   input  active-high 
	line   3:      unnamed       unused   input  active-high 
	line   4:      unnamed       unused   input  active-high 
	line   5:      unnamed       unused   input  active-high 
	line   6:      unnamed       unused   input  active-high 
	line   7:      unnamed       unused   input  active-high 
	line   8:      unnamed       unused   input  active-high 
	line   9:      unnamed       unused   input  active-high 
	line  10:      unnamed       unused   input  active-high 
	line  11:      unnamed       unused   input  active-high 
	line  12:      unnamed       unused   input  active-high 
	line  13:      unnamed       unused   input  active-high 
	line  14:      unnamed       unused  output  active-high 
	line  15:      unnamed       unused   input  active-high 
	line  16:      unnamed       unused   input  active-high 
	line  17:      unnamed       unused   input  active-high 
	line  18:      unnamed       unused   input  active-high 
	line  19:      unnamed       unused   input  active-high 
	line  20:      unnamed       unused   input  active-high 
```

5. flutter_gpio_test - **WORK**
```
flutter: Button: SignalEvent(edge: rising, time: 2020-05-22 18:05:27.935929)
flutter: Button: SignalEvent(edge: falling, time: 2020-05-22 18:05:28.065014)
flutter: Button: SignalEvent(edge: rising, time: 2020-05-22 18:05:28.065029)

```

PS: **lsgpio**

> -bash: lsgpio: command not found

**Comment by DisDis** [comment]
1. python
2  gpioinfo (Done in parallel)
show:
```
gpiochip0 - 54 lines:
	line   0:      unnamed       unused   input  active-high 
	line   1:      unnamed       unused   input  active-high 
	line   2:      unnamed       unused   input  active-high 
	line   3:      unnamed       unused   input  active-high 
	line   4:      unnamed       unused   input  active-high 
	line   5:      unnamed       unused   input  active-high 
	line   6:      unnamed       unused   input  active-high 
	line   7:      unnamed       unused   input  active-high 
	line   8:      unnamed       unused   input  active-high 
	line   9:      unnamed       unused   input  active-high 
	line  10:      unnamed       unused   input  active-high 
	line  11:      unnamed       unused   input  active-high 
	line  12:      unnamed       unused   input  active-high 
	line  13:      unnamed       unused   input  active-high 
	line  14:      unnamed       unused  output  active-high 
	line  15:      unnamed      "sysfs"   input  active-high [used]
	line  16:      unnamed       unused   input  active-high 
	line  17:      unnamed       unused   input  active-high 
	line  18:      unnamed       unused   input  active-high 
	line  19:      unnamed       unused   input  active-high 
	line  20:      unnamed       unused   input  active-high 
```

**Comment by DisDis** [comment]
1. reboot
2. gpiomon 0 15  (**NOT WORK**)
show one line afrer start:
`event:  RISING EDGE offset: 15 timestamp: [1590167527.152324171]`
it has no reaction to the button.
3. pyhton 
4. gpiomon 0 15 (**WORK**)
```
event:  RISING EDGE offset: 15 timestamp: [1590167703.365183150]
event: FALLING EDGE offset: 15 timestamp: [1590167703.465209714]
event:  RISING EDGE offset: 15 timestamp: [1590167703.590902842]
event: FALLING EDGE offset: 15 timestamp: [1590167703.672518533]
```

**Comment by ardera** [comment]
That's strange, but if it doesn't work with `gpiomon` this is out of my scope.
You can try getting your system up to date using `sudo apt update` and `sudo apt upgrade`, but I'm not sure that'll help.
If the issue persists, it's best opening an issue on the [raspbian kernels github repo](https://github.com/raspberrypi/linux).

**Comment by MrCustomizer** [comment]
I think I've figured out, what went wrong here. The button probably didn't have a pull-down resistor and relied on the pull-down functionality of the GPIO controller.
Handling of pull-down resistors is a pretty new feature in gpiod, though. According to [this source](https://microhobby.com.br/blog/2020/02/02/new-linux-kernel-5-5-new-interfaces-in-gpiolib/) you need at least a kernel with version 5.5.0 and libgpiod in version 1.5. Raspbian currently has a 5.4 kernel and libgpiod is currently at v1.2. So this currently just doesn't work in Raspbian. We will have to wait for the kernel update and a newer version of libgpiod to land in Raspbian (another option should be compiling your own kernel and libgpiod).
It would be nice if this feature could be added to flutter-gpiod, when it lands in Raspbian.

**Comment by ardera** [comment]
> It would be nice if this feature could be added to flutter-gpiod, when it lands in Raspbian.

It's actually included already. It's called [`Bias`](https://pub.dev/documentation/flutter_gpiod/latest/flutter_gpiod/Bias-class.html). The `GpioLine.requestInput`, `GpioLine.requestOutput`, `GpioLine.reconfigureInput` and `GpioLine.reconfigureOutput` functions all have a `bias` argument. There's [`FlutterGpiod.supportsBias`](https://pub.dev/documentation/flutter_gpiod/latest/flutter_gpiod/FlutterGpiod/supportsBias.html), which returns `true` if bias is supported on the platform (which is the case when the linux kernel version is >= 5.5)
