### ISSUE TITLE
No implementation found for method getNumChips

### ISSUE THREAD

**Issue by jlia0** [ardera/flutter_gpiod#9]
[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method getNumChips on channel plugins.flutter.io/gpiod)

I used the flutter_gpiod package (^0.1.0+3) and tested on RPi which is running LineageOS 16.0 (Android 9)

**Comment by jlia0** [comment]
I ran the repo and there is a new error coming out.

E/flutter ( 2644): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library (dlopen failed: library "libc.so.6" not found)

**Comment by ardera** [comment]
Sorry, this plugin is only really meant for use on linux. (more precisely, GNU/Linux)
- Versions 0.1.x functioned using some platform-side code and method channels, which is why you get the `MissingPluginException`. (The platform-side code is not present on android. It's only present when running on Linux using [flutter-pi](https://github.com/ardera/flutter-pi))
- Versions 0.2.x use `dart:ffi`, so they don't require any platform-side code. But it still needs `libc`. The default name for `libc` on GNU/Linux is `libc.so.6`. I can add a fallback to `libc.so` (which should be the name on Android), but even then it may not work since android typically uses older linux kernels, and the GPIO character device interface is fairly new.

EDIT: Okay, just implemented the fallback. Can you try again with latest master? If the number of GPIO chips reported by `flutter_gpiod` is zero, the GPIO character device interface is probably not supported by your kernel.

**Comment by jlia0** [comment]
> Sorry, this plugin is only really meant for use on linux. (more precisely, GNU/Linux)
> 
> * Versions 0.1.x functioned using some platform-side code and method channels, which is why you get the `MissingPluginException`. (The platform-side code is not present on android. It's only present when running on Linux using [flutter-pi](https://github.com/ardera/flutter-pi))
> * Versions 0.2.x use `dart:ffi`, so they don't require any platform-side code. But it still needs `libc`. The default name for `libc` on GNU/Linux is `libc.so.6`. I can add a fallback to `libc.so` (which should be the name on Android), but even then it may not work since android typically uses older linux kernels, and the GPIO character device interface is fairly new.
> 
> EDIT: Okay, just implemented the fallback. Can you try again with latest master? If the number of GPIO chips reported by `flutter_gpiod` is zero, the GPIO character device interface is probably not supported by your kernel.

Thank you so much! I have tested the latest branch and it seems that the library is working well but there is another error:

`E/flutter ( 1794): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: FileSystemException: Could not open GPIO chip 0, path = '/dev/gpiochip0'`

I am currently using [LineageOS 16.0 (Android 9)](https://konstakang.com/devices/rpi4/LineageOS16.0/). The kernel version is 4.19.84-v7l-gbb8964f5d42a. In the description, the OS supports GPIO and I checked the docs it provides GPIO access through `/sys/class/gpio`. However, I checked that there is a file in the path of `/dev/gpiochip0`. Is it because of the root access that the App got the FileSystemException?

I could potentially use the latest LineageOS version, which uses the kernel version of 5.4.53-v7l-gec4651cc1015.

**Comment by GoRadioGo** [comment]
May or may not address your issue:
https://pypi.org/project/gpiodev/
This library doesn't require root access to the system, but it needs a read-write access to the gpiochip device. 
By default it uses /dev/gpiochip0.
To allow read-write access to the device for the user, run:

$ sudo chmod a+rw /dev/gpiochip0

**Comment by ardera** [comment]
> The kernel version is 4.19.84-v7l-gbb8964f5d42a.

Okay, that should work.

> In the description, the OS supports GPIO and I checked the docs it provides GPIO access through `/sys/class/gpio`.

Yeah, the sysfs interface is the old one. The `/dev/gpiochipX` interface is the new one.

> Is it because of the root access that the App got the FileSystemException?

Yeah, that's possible. It looks like a permissions issue for me. I think `chmod a+rw /dev/gpiochip0` only works until reboot, but it's good for trying it out. For a permanent solution, you could find out the owner group of the `/dev/gpiochip0` file (using `ls -l`) and add your user to that.
[This](https://stackoverflow.com/questions/47131267/aosp-device-node-access-permissions) may also work

**Comment by jlia0** [comment]
> > The kernel version is 4.19.84-v7l-gbb8964f5d42a.
> 
> Okay, that should work.
> 
> > In the description, the OS supports GPIO and I checked the docs it provides GPIO access through `/sys/class/gpio`.
> 
> Yeah, the sysfs interface is the old one. The `/dev/gpiochipX` interface is the new one.
> 
> > Is it because of the root access that the App got the FileSystemException?
> 
> Yeah, that's possible. It looks like a permissions issue for me. I think `chmod a+rw /dev/gpiochip0` only works until reboot, but it's good for trying it out. For a permanent solution, you could find out the owner group of the `/dev/gpiochip0` file (using `ls -l`) and add your user to that.
> [This](https://stackoverflow.com/questions/47131267/aosp-device-node-access-permissions) may also work

Thank you! It is the root access issue and it works now on Android!

`I/flutter ( 2740): GpioChip(index: 0, name: 'gpiochip0', label: 'pinctrl-bcm2835', numLines: 54)`
`I/flutter ( 2740): GpioChip(index: 1, name: 'gpiochip1', label: 'raspberrypi-exp-gpio', numLines: 8)`

However, there is still an error:
`E/flutter ( 2740): [ERROR:flutter/runtime/dart_isolate.cc(865)] Unhandled exception:`
`E/flutter ( 2740): Invalid argument(s): Failed to load dynamic library (dlopen failed: library "libc.so.6" not found)`

**Comment by ardera** [comment]
> However, there is still an error:
> `E/flutter ( 2740): [ERROR:flutter/runtime/dart_isolate.cc(865)] Unhandled exception:`
> `E/flutter ( 2740): Invalid argument(s): Failed to load dynamic library (dlopen failed: library "libc.so.6" not found)`

Oh, I know why. `libc.so` is actually loaded two times, and I forgot to add the android fallback to the second time `libc.so` is loaded

**Comment by ardera** [comment]
Just fixed that.

@JLiao98 How did you fix the permissions problem? That may be useful to others in the future

**Comment by jlia0** [comment]
> Just fixed that.
> 
> @JLiao98 How did you fix the permissions problem? That may be useful to others in the future

I fixed the permission problem by doing `chmod a+rw /dev/gpiochip0`. However, like you said it's not permanent. So I tried out editing the `init.rc` file, and add `chmod a+rw /dev/gpiochip0` and `chmod a+rw /dev/gpiochip1` to the `on boot` section.

**Comment by ardera** [comment]
flutter_gpiod uses ffi now, so this should work
